cluster:
  name: frontend-dev
  address: https://kubernetes.default.svc
appBundle:
  targetRevision: main
values: |
  global:
    prediktor:
      domain: frontend.dev.powerview.io
    vswh:
      annotations: &vault-annotations
        vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-role: powerview
        vault.security.banzaicloud.io/vault-skip-verify: "true"
  postgres:
    enabled: true
    targetRevision: 12.1.15
    commonAnnotations:
      *vault-annotations
    global:
      postgresql:
        auth:
          postgresPassword: vault:powerview/data/psql#password
    primary:
      extraEnvVarsSecret: frontendtwin-secret
      initdb:
        scripts:
          init.sh: |
            PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres -h 127.0.0.1 $POSTGRES_DB <<EOF
            DO
            \$do\$
            BEGIN
              IF NOT EXISTS (
                  SELECT FROM pg_catalog.pg_roles WHERE rolname = 'FrontendTwin'
              ) THEN
                  CREATE ROLE "FrontendTwin" WITH LOGIN NOSUPERUSER CREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD '${FRONTENDTWIN_PASSWORD}';
                  GRANT "FrontendTwin" TO psqladmin WITH ADMIN OPTION;
              END IF;
            END
            \$do\$;
            EOF
  preInstall:
    enabled: false
    grafana:
      clientId: vault:powerview-frontend-dev/data/SP-Grafana#application_id
      clientSecret: vault:powerview-frontend-dev/data/SP-Grafana#value
      adminUser: vault:powerview-frontend-dev/data/grafana#adminUser
      adminPassword: vault:powerview-frontend-dev/data/grafana#adminPassword
    certManagerAzure:
      clientSecret: vault:powerview-frontend-dev/data/bootstrap#azure-client-secret.json
    externalDNS:
      clientSecret: vault:powerview-frontend-dev/data/bootstrap#azure.json
