---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/gostomski/argoproj.git
    path: helm-guestbook/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=false
    - CreateNamespace=false 
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
